### PR TITLE
Add some javascript frameworks.

### PR DESCRIPTION
**Pull request by ProgVal**
As noted in #381, this project clearly lacks of JS frameworks.

### CODE REVIEW

**Comment by mrkrstphr** [comment]
too many files. can't review. can't tell if you're a dick. assuming.

**Comment by ProgVal** [comment]
:(

**Comment by KokaKiwi** [comment]
:(

**Comment by eramdam** [comment]
:(

**Comment by ProgVal** [comment]
Should I separate this into multiple pull requests?

**Pull request closed without merging**
