### PR TITLE
Create 7.rb

### PR DESCRIPTION
**Pull request by karandesai-96**
Counting Counting Counting !

(Just for fun :grin: )

### CODE REVIEW

**Comment by GLolol** [comment]
Please use the code/ folder.

**Comment by karandesai-96** [comment]
Oh okay :+1:

**Comment by karandesai-96** [comment]
@GLolol what about this: https://github.com/illacceptanything/illacceptanything/tree/master/counter

**Comment by GLolol** [comment]
That works too.

**Pull request merged**
