### PR TITLE
some fart refactoring and add composer to ass module

### PR DESCRIPTION
**Pull request by seyfer**

### CODE REVIEW

**Comment by ProgVal** [comment]
Do you actually need PHP 5.4, a framework, and a file system mock to do that in PHP?

**Comment by seyfer** [comment]
@ProgVal , yes and it's not completed list of dependencies.

**Comment by seyfer** [comment]
@ProgVal I think in better case all possible dependencies should be included for this project.

**Comment by ProgVal** [comment]
We're planning on writing our own OS for that

**Comment by GLolol** [comment]
How big are these commits? LGTM otherwise.

**Comment by ProgVal** [comment]
> How big are these commits?

They are ok. What's the issue?

> LGTM otherwise.

“LGTM”?

**Comment by GLolol** [comment]
Looks Good To Me.

**Pull request merged**
