### PR TITLE
Create Kezzap

### PR DESCRIPTION
**Pull request by casseroo**
Hahaha

### CODE REVIEW

**Comment by ProgVal** [comment]
Waiting for #605

**Comment by casseroo** [comment]
Ok, accept it now. I will refactor it shortly.

**Comment by casseroo** [comment]
Thanks, have refactored! Ready to pull :)

From the sexiest girl in Jamaica. :+1:

**Comment by GLolol** [comment]
Please sort your files into the `data/` folder for documents, it prevents to repository root from being a mess.

**Comment by casseroo** [comment]
We need this file to be in the root because we have upstream deps 

Please accept this PR what is this the apple app review team?!

Thanks, much love

The sexiest girl in Jamaica

Bosh

:+1:

**Comment by casseroo** [comment]
All the tests are passing btw

**Comment by GLolol** [comment]
:-1:

**Comment by casseroo** [comment]
Ok I'll move the file. Will you accept the PR then?

**Comment by GLolol** [comment]
Yes, please wait for #605 though...

**Comment by casseroo** [comment]
yo, the sexiest girl in jamaica has done it yo

**Comment by casseroo** [comment]
Bump

Sexiest girl in Jamaica

**Comment by GLolol** [comment]
Merged in b24c3b730338fad88adf59e9d7027df7e580bc0e.

**Pull request closed without merging**
