### PR TITLE
How to properly contribute to this repository

### PR DESCRIPTION
**Pull request by jonduarte**
Explains step by step how to contribute with the repo.

### CODE REVIEW

**Comment by GLolol** [comment]
It's `rm -r illacceptanything` for folders.

**Comment by jonduarte** [comment]
I thought you'd accept anything :disappointed:

**Comment by dlibanori** [comment]
So you don't accept anything...

**Comment by GLolol** [comment]
Changed my mind: cherry-picked in 701a1593cebdf0111cfd8064164dc37c87b074a6 and fixed in eb4f73d3efa74f5a73f41060efc6ebe88d6baa63.

**Pull request closed without merging**
