### PR TITLE
Add a recursive submodule

### PR DESCRIPTION
**Pull request by Ape**

### CODE REVIEW

**Comment by ProgVal** [comment]
Note: this was already done in #316, but removed in a3c17e72041ad7e42c006d49776011957a0deabe because the name of the URL changed.

**Comment by GLolol** [comment]
Weren't there issues with some clients recursively downloading the submodule and never finishing? #639

**Comment by ProgVal** [comment]
unlikely. The submodule necessarily points to a *parent* commit.

**Comment by ProgVal** [comment]
unlikely. The submodule necessarily points to a **older** commit.

**Pull request merged**
