### PR TITLE
Add /dev/zero emulation layer

### PR DESCRIPTION
**Pull request by iblue**
Adds a `/dev/zero` emulation layer.

### CODE REVIEW

**Comment by ProgVal** [comment]
Could you add a script that generates an infinite stream of zeros instead?

**Comment by iblue** [comment]
100 MB ought to be enough zeros for anybody. No need for a script.

**Comment by ProgVal** [comment]
Not if I want to use it to wipe my disk

**Comment by iblue** [comment]
If you wipe the first 100 MB, you should be fine.

**Comment by GLolol** [comment]
Man. RIP my Internet.

**Pull request merged**
