### PR TITLE
Jabbascripts

### PR DESCRIPTION
**Pull request by ppiekarczyk**
document.ready

### CODE REVIEW

**Comment by popey456963** [comment]
Appears to play the Harlem Shake - http://pastebin.com/v7X2MmUU

**Comment by ppiekarczyk** [comment]
Yes, it does

**Comment by GLolol** [comment]
I think it's time `index.html` gets rewritten with an actual navigation to the web based sites here. Will merge as part of that then.

**Comment by popey456963** [comment]
This is a rather snazzy menu screen - https://gist.github.com/popey456963/d904a7a2f8e228857da4

**Comment by GLolol** [comment]
It's sitting there cloning on my home machine. :)

**Comment by GLolol** [comment]
Merged. I decided to import all the dependencies (mp3 and css) used by the script into the repository itself, for safekeeping in case the original site goes down. I hope this is a reasonable change.

**Pull request closed without merging**
