### PR TITLE
Organized data folder for Issue #655.

### PR DESCRIPTION
**Pull request by initbar**
Sorry for the late change. Here is the restructured data folder.

I didn't touch the files inside existing folders (but the rogue ones outside).

### CODE REVIEW

**Comment by GLolol** [comment]
:-1: on mixing the dictionary with everything else.

**Comment by GLolol** [comment]
Ditto with the French civil code .md files.

**Comment by initbar** [comment]
Shoot - I've used `find -exec` to just batch move by file extensions.

**Comment by initbar** [comment]
Can I have a list of files? I'll fix it.

**Comment by GLolol** [comment]
I highly recommend keeping the directory structure for any folder in `data/` that has multiple files inside. Be sure to note conflicts because many directories have a README.md. file present.

**Comment by initbar** [comment]
Alright - I'll first fix the dictionary right now.

**Comment by GLolol** [comment]
To be frank, I don't really see the benefit of sorting files by extension instead of file type. For example, .md, .txt, and files in ascii/ are all really just text files. .PNG, .jpg, and .gif files could all be grouped into media/

I think this folder structure would work better:

* doc/
* media/
* html (though we have a separate web/ folder, maybe just use that instead)
* misc/

**Comment by initbar** [comment]
Sounds good: so how does this sound?

1) Don't touch existing directories inside `data` (i.e. `dictionary`).
2) Move rogue files not inside any directories.

Just so that I have a clear picture, which subdirectories are "off-limits?"

**Comment by GLolol** [comment]
I would just worry about files in the folder root for now.

**Comment by initbar** [comment]
coolbeans - I'll close this and create a new pull request.

**Comment by GLolol** [comment]
Did you see my suggestion on sorting by file type instead of extension?

**Comment by initbar** [comment]
Yup

**Comment by initbar** [comment]
Will be done that way.

**Pull request closed without merging**
