### PR TITLE
Importing Linux; we'll need it.

### PR DESCRIPTION
**Pull request by kyleterry**

### CODE REVIEW

**Comment by recurrence** [comment]
:+1:  Approved.  Creator please merge.

**Comment by hrj** [comment]
:boom: :point_left:

**Comment by kyleterry** [comment]
:+1: approved

**Comment by qpfiffer** [comment]
:package:

**Comment by lykkin** [comment]
:shipit:

**Comment by kyleterry** [comment]
:package: :shipit:

**Comment by lykkin** [comment]
this pr promotes freedom and justice

**Comment by kyleterry** [comment]
GNU

**Comment by micahlmartin** [comment]
#gnu

**Comment by GLolol** [comment]
I knew that someone would do something like this! Why not use a submodule to lessen bandwidth usage?

**Comment by kyleterry** [comment]
Where's the fun in that?

**Comment by GLolol** [comment]
The repository is now over 100MB. :cold_sweat:

**Comment by lykkin** [comment]
@GLolol do it for him

**Comment by kyleterry** [comment]
All hail Torvalds. All hail Torvalds. All hail Torvalds. All hail Torvalds. All hail Torvalds. All hail Torvalds.

**Pull request merged**
