### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by weswigham**
For running all this nonsense in a container because containers.

### CODE REVIEW

**Comment by mrkrstphr** [comment]
Uh oh, conflicts.

**Comment by icecrime** [comment]
:+1:

**Comment by ProgVal** [comment]
:+1:

**Comment by GLolol** [comment]
There seems to be already a Dockerfile. Can't automagically merge :(

**Comment by bithavoc** [comment]
pls fix conflicts.

**Pull request closed without merging**
