### PR TITLE
Added support for the Linux kernel.

### PR DESCRIPTION
**Pull request by AlexGitReid**
Finally, adding support for Linux 2.6.37-rc3. It has been sorely missing.

### CODE REVIEW

**Comment by JohnDvorak** [comment]
LGTM

**Comment by Josaphat** [comment]
:+1:  LGTM

**Comment by lezama** [comment]
:)

**Comment by bithavoc** [comment]
pls fix conflict

**Comment by kyleterry** [comment]
Yo, did that already. Later!

**Comment by recurrence** [comment]
I think the kernel was already merged :)

**Comment by AlexGitReid** [comment]
Glad that it's already merged!

**Comment by recurrence** [comment]
For Great Linus!

**Pull request closed without merging**
