### PR TITLE
Added a test in shell

### PR DESCRIPTION
**Pull request by rilut**
Actually I'm not sure of this one

### CODE REVIEW

**Comment by ProgVal** [comment]
Please parse the JSON file instead of just comparing it to `'[]'`.
An empty list may be serialized as `'[ ]'` as well.

(see #346)

**Comment by rilut** [comment]
@ProgVal oh cool now I know the reason why

**Comment by ProgVal** [comment]
The reason of what?

**Comment by rilut** [comment]
To parse the json first

**Comment by ProgVal** [comment]
Actually, using `s/\s//g` and removing newlines should be fine

**Comment by rilut** [comment]
@ProgVal Thanks for the insights!

**Pull request merged**
