### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by larryhan**

### CODE REVIEW

**Comment by mzemel** [comment]
What a conundrum.

**Comment by bitops** [comment]
That's clearly gaming the system.

**Comment by larryhan** [comment]
A pervious (inferior may I add) implementation of this was rejected: https://github.com/mrkrstphr/illacceptanything/pull/5

Hopefully my better commit message and implementation of this change will be accepted.

**Comment by mzemel** [comment]
I hope not.  Be the contributor Mr Rogers knows you can be.

**Pull request closed without merging**
