### PR TITLE
Bogan pride

### PR DESCRIPTION
**Pull request by JordyValentine**
Just adding my mark to this awesome project

this plays a full page youtube video [https://www.youtube.com/watch?v=Ul_krInglTw](https://www.youtube.com/watch?v=Ul_krInglTw) 

put simply, it's a music video about drinking beer from shoes

### CODE REVIEW

**Comment by JordyValentine** [comment]
i didnt know where I should put the file so I just put it at the root of the repo

**Comment by JordyValentine** [comment]
Hi @jlu5 can I ask why this is invalid?

**Comment by jlu5** [comment]
The invalid tag is a thing from previous Hacktoberfests to discourage spamming submissions here.

**Comment by JordyValentine** [comment]
Ah okay, that makes sense. Thought I had do something wrong 😁️ thanks for merging this

On 14 October 2019 4:16:11 am AEDT, James Lu <notifications@github.com> wrote:
>The invalid tag is a thing from previous Hacktoberfests to discourage
>spamming submissions here. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/illacceptanything/illacceptanything/pull/949#issuecomment-541437423

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
