### PR TITLE
Added virus.txt

### PR DESCRIPTION
**Pull request by LuRsT**
A file to test whether the anti-virus works

### CODE REVIEW

**Comment by mileswd** [comment]
Duplicate of #228, essentially? :wink:

**Comment by LuRsT** [comment]
@mileswd , oh yeah, didn't see that one there! Should I close this one or keep it since he accepts anything? xD

**Comment by mileswd** [comment]
May as well keep it now :blush: :+1:

**Comment by mileswd** [comment]
(Taking advice from this gif, of course :smile:)

**Comment by LuRsT** [comment]
Awesome!

**Pull request merged**
