### PR TITLE
added Chile-Parrot

### PR DESCRIPTION
**Pull request by juanbrujo**

### CODE REVIEW

**Comment by ProgVal** [comment]
May I ask how you found that repo? We've got a lost of PRs the last hour and I'm curious about its origin.

**Comment by juanbrujo** [comment]
Twitter, I'm trying to find which one.

**Comment by juanbrujo** [comment]
this -> https://twitter.com/mikko/status/752583421482897409

**Comment by ProgVal** [comment]
thanks :)

**Pull request merged**
